### ISSUE TITLE
Move opportunities page to Django templates

### ISSUE THREAD

**Issue by sagesharp** [outreachy/website#132]

**Comment by manaswinidas** [comment]
I went through all the links in the opportunities list. The following links aren't working:
1. Open Source Robotics Foundation link leads to a `Sorry page`
2. Codethink leads to a 404 error page
3. Elego which should land to its home page, leads to a 404 page
4. KDAB leads to a `Sorry page`
5. NESCent's partners link leads to a 404 page
6. Sumana Harihareswara's round-up of NYC orgs and Dec 2012 links lead to 'This page doesn't exist yet' GNOME page

**Comment by C-Lion** [comment]
I want to work on this issue please. I will look up links to the main pages for items 2 & 3, but I assume there are there more specific links than just the home pages for the rest?

**Comment by sagesharp** [comment]
(This issue wasn't well defined, and got out-of-date. I'm updating it before the PyCon U.S. sprints. Sorry to anyone who commented on this issue but didn't get an answer! If you want to work on this again, please feel free to do so.)

The opportunities page at https://www.outreachy.org/opportunities/ is currently a page under the Wagtail CMS that we use. That means it's not currently in the Outreachy website source code (instead, it's stored in the CMS database). We need to move it to a new Django page in the source code.

Create a new template `home/templates/home/opportunities.html`. For now, you can keep the page laid out the same way as the old page. You should set up the page with similar header tags and blocks like `home/templates/home/travel_stipend.html`. Use the same level of headers as that page. Duplicate the current page's HTML (right click and 'View source' will help here). Only duplicate the headers, paragraphs, and lists on the pages. The other HTML content will be automatically added by the base.html template.

Once you've got that template, it's time to add a view. Look at the `travel_stipend` function in `home/views.py`. Make a similar function that displays your new template. You don't need to pass in the rounds variable.

Next, you need to make Django call into your view when a particular URL is accessed. Edit `home/urls.py`. If you search for `travel_stipend`, you'll see where you need to add a pattern matching expression for your new template page.

Commit your changes, including the new template file. Then make a second commit that removes any links that are broken. I want to have the second commit so I have a list of which links we need to track down new versions of.

Bonus Stuff
---

As a side note, I don't think the current layout of the page is something we can maintain. We don't have good records of how many interns a company or community sponsored before Outreachy joined the Software Freedom Conservancy. Therefore, we can't calculate how many interns each sponsor has sponsored. What I do have access to (probably) is a list of sponsors and their sponsorship levels. I would like to rearrange this page with sections for Ceiling Smasher, Equalizer, Promoter, and Includer level sponsors. Any sponsor who has been at a particular level in the past stays at that level. I would need time to gather information about our past sponsors to make sure they're at the right prominence, which is why this is a stretch goal.

I also want to add resources like jobs boards for people who are underrepresented in tech. The ones I know of are:

 - [Blacks in Tech jobs board](https://www.blacksintechnology.net/jobs-board/)
 - [People of Color in Tech jobs board](https://www.pocitjobs.com/)
 - [Women Who Code jobs board](https://www.womenwhocode.com/jobs/)
 - [American Indian Science and Engineering Society](https://careers.aises.org/)

**Comment by KunyiLiu** [comment]
Working on that today
