### ISSUE TITLE
Fix typo in field help text for eligibility form

### ISSUE THREAD

**Issue by sagesharp** [outreachy/website#154]
@withshubh reported this bug:
> There is a typo in the eligibility check form.
> 
> Are you a national or permanent resident of the United States of America?
Outreachy is open to some people around the world, and additional *grpous* of
people in the U.S.A.

This is a good bug for people who are new to Django, who are somewhat familiar with running commands from the command line, and who are slightly familiar with Python.

You'll need to follow the "Setting up your development environment instructions" in the [README.md](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/README.md) file, following instructions through the end of the "Testing the local website" section. Once you do, you'll be able to navigate to your local copy of the http://127.0.0.1:8000/eligibility/ form to see your local instance of the form. Any changes you make to your local code base will be automatically updated on the copy of the Outreachy website running on your local machine.

Each form on the Outreachy website is associated with one or more Django models. A model is a Python class that represents the form, with fields, the type of data that can be entered into that field, and the help text that is associated with that field.

Fixing this requires changing the help_text of that field (us_national_or_permanent_resident) in [models.py](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/models.py#L1283). 

This change is a change to the Django [model](https://docs.djangoproject.com/en/1.11/topics/db/models/), so you'll need to create a new [migration](https://docs.djangoproject.com/en/1.11/topics/migrations/). Then commit both the model.py and the migration file created under [home/migrations/](https://github.com/sagesharp/outreachy-django-wagtail/blob/master/home/migrations/).

Good luck! I'm leaving this bug here for people new to Django to fix. Don't fix this if you're already familiar with Django.

**Comment by kanglicheng** [comment]
working on this (pycon sprints session)

**Comment by withshubh** [comment]
No experience in Django.
Still taking this issue! wish me luck 😉

**Comment by withshubh** [comment]
@sagesharp I thinks it's okay to close this issue as this typo doesn't exist anymore. It's fixed already.
