### ISSUE TITLE
Tell applicants to set a filter in Gmail

### ISSUE THREAD

**Issue by sagesharp** [outreachy/website#285]
As soon as an applicant finishes filling out their application, ask them to set a filter in gmail to put all Outreachy email into their Inbox.

We've had applicants email us asking why their application wasn't acted on. Sometimes it's because emails about their applications end up in the Gmail Promotions or Updates tab.

One solution to this is to tell applicants after their initial application is filled out to set a Gmail filter. The filter should put all Outreachy email into their Inbox. Here is some default text you can use:

"Set your email filters

Please set an email filter to ensure you can receive emails from Outreachy organizers. If you use Gmail, please set a filter to ensure all messages from:outreachy.org will go to your Inbox, rather than to your Promotions or Updates tabs."

The place that this text should be displayed is the initial application results page. The template for that page is in `home/templates/home/eligibility_results.html`. If the ApplicantApproval object is set to the pending state (rather than being automatically rejected), then the website should display this text. Put the text in a card div with an warning color header. You can find an example of a div card with a warning header in the eligibility prompt snippet `home/templates/home/snippet/eligibility_prompt.html`

In order to test your code:
 * [Make a new round with the contribution period open](https://github.com/sagesharp/outreachy-django-wagtail#setting-up-a-new-internship-round), following the instructions in README.md.
 * [Create a coordinator account under a new community](https://github.com/sagesharp/outreachy-django-wagtail#coordinatorapproval-class).
 * [Create a Participation object](https://github.com/sagesharp/outreachy-django-wagtail#participation-and-sponsorship-classes) that has the community participating in the newly created round.
 * [Create a project under the community with a mentor](https://github.com/sagesharp/outreachy-django-wagtail#project-and-mentorapproval-classes).
 * [Create an applicant with an ApplicantApproval](https://github.com/sagesharp/outreachy-django-wagtail#creating-applicantapproval-test-objects). Instead of setting the approval_status to approved, set it to pending.
 * [Start the local test website server](https://github.com/sagesharp/outreachy-django-wagtail#testing-the-local-website)

You can then test your changes by logging in as the applicant and going to `localhost:8000/eligibility-results/` to ensure the new text shows up. If you then use the Django shell to set the approval status to approved, the text should still be there. The text should not be there if the application status is rejected.

**Comment by eechien** [comment]
Looking into this one...
