### ISSUE TITLE
Prompt applications on the website when application needs an update

### ISSUE THREAD

**Issue by sagesharp** [outreachy/website#286]
Outreachy applicants need to fill out an initial essay. Sometimes that essay is unclear, and the Outreachy organizers need to ask applicants to revise their essay. Applicants often don't notice that email because it ends up in their Gmail Promotion or Updates tab.

There should be a prompt on the Outreachy website when they log in if they need to revise their essay. Many of the pages on the Outreachy website display a series of prompts to encourage applicants to take the next steps (such as filling on an initial application, picking a project, recording a contribution, creating a final application, etc). Add text to those prompts if the applicant needs to update their essays or school information.

The template logic to pick which prompt to display is in `home/templates/home/snippet/eligibility_prompts.html`. The relevant prompt is the `home/templates/home/snippet/pending_prompt.html` template. To check whether an application has been marked by the Outreachy organizers as needing a revision, you can check whether `applicantapproval.barrierstoparticipation.applicant_should_update` is set to True. If so, display the message:

"You need to update your essay questions. The Outreachy organizer found them unclear or not having enough information."

The "update your essay questions" should be a link to the URL to edit their essay. You can find an example of how to construct that link in the essay revision reminder email at `home/templates/home/email/applicant-essay-needs-updated.txt`.

In order to test your changes, you'll need to:

 * [Make a new round with the contribution period open](https://github.com/sagesharp/outreachy-django-wagtail#setting-up-a-new-internship-round), following the instructions in README.md.
 * [Create a coordinator account under a new community](https://github.com/sagesharp/outreachy-django-wagtail#coordinatorapproval-class).
 * [Create a Participation object](https://github.com/sagesharp/outreachy-django-wagtail#participation-and-sponsorship-classes) that has the community participating in the newly created round.
 * [Create a project under the community with a mentor](https://github.com/sagesharp/outreachy-django-wagtail#project-and-mentorapproval-classes).
 * [Create an applicant with an ApplicantApproval](https://github.com/sagesharp/outreachy-django-wagtail#creating-applicantapproval-test-objects)
 * Use the Django shell to set ApplicantApproval.barrierstoparticipation.applicant_should_update to True
 * [Start the local test website server](https://github.com/sagesharp/outreachy-django-wagtail#testing-the-local-website)

Then test to see whether an applicant sees the prompt when their essay needs to be revised. Log in as the applicant. Go to your dashboard `localhost:8000/dashboard`. You should see a prompt to update your essay questions. Update your essay questions, and then go back to the dashboard. The prompt shouldn't show you need to update your essay.

**Comment by eechien** [comment]
I'm looking into this one...
