### ISSUE TITLE
Add tests for mentors selecting interns

### ISSUE THREAD

**Issue by sagesharp** [outreachy/website#290]
As #288 shows, we need to add automated tests for ensuring mentors can select an intern. Ideally this test would take the intern selection through the full cycle of review:

1. Mentor selects intern.
2. Coordinator sets who will pay for this intern (the funding source).
3. Organizer approves the intern.

Other good things to test:

1. Mentors should be able to select an intern at any point from when the projects are shown until the intern selection deadline.
2. Organizers shouldn't be able to approve the intern until the coordinator sets the funding source (all Outreachy interns should be funded).

**Comment by djmitche** [comment]
I'd like to work on this during the sprints..

**Comment by djmitche** [comment]
Fixed in #325.

**Comment by sagesharp** [comment]
Thank you! :blue_heart:
