### ISSUE TITLE
Ask a yes/no question in final application about GSoC

### ISSUE THREAD

**Issue by sagesharp** [outreachy/website#301]
In the final application, we ask applicants to provide contact information for the mentors they're working with in GSoC. We ask them to leave it blank if they're not applying to GSoC. Then, based on whether the answer is blank, we display "Yes" in a column in the Outreachy organizer's dashboard for whether the applicant has applied to GSoC. I think we also display "Yes" in the community's applicant summary page.

The problem is, applicants often don't leave the question blank. They say things like, "I'm not applying this year," or "N/A". That means the tables say "Yes" the applicant is applying to GSoC when they're not.

Add a new Yes/No question on the final application, "Are you applying to Google Summer of Code?" Display that question in the applicant's final application form. Display the answer to that question in the organizer applicant tables, and in the details section of the project applicants page.

**Comment by senjutibala** [comment]
@sagesharp can I work on the issue?
