### ISSUE TITLE
Coordinator contacts need commas on project page

### ISSUE THREAD

**Issue by sagesharp** [outreachy/website#303]
On the Outreachy project pages, there's a list of coordinators for the community. If you're logged in, that includes the coordinators' email addresses. I would like to be able to grab all the emails and paste them into my mail client's To header. Unfortunately, right now, the coordinator list is separated by a space, not a comma. That means I have to edit the information each time I paste it.

The section that needs to change is the "How do I get help?" section in [home/templates/home/snippet/project_landing_snippet.html](https://github.com/sagesharp/outreachy-django-wagtail/blob/263e5f191b75fcdb141f90b0bf1fa2fce4477247/home/templates/home/snippet/project_landing_snippet.html#L158) The coordinator list is correctly formatted with commas in `home/templates/home/community_read_only.html`

**Comment by sagesharp** [comment]
To test your code:

 * [Make a new round with the contribution period open](https://github.com/sagesharp/outreachy-django-wagtail#setting-up-a-new-internship-round), following the instructions in README.md.
 * [Create two or more coordinator accounts under the same community](https://github.com/sagesharp/outreachy-django-wagtail#coordinatorapproval-class).
 * [Create a Participation object](https://github.com/sagesharp/outreachy-django-wagtail#participation-and-sponsorship-classes) that has the community participating in the newly created round.
 * [Create a project under the community with a mentor](https://github.com/sagesharp/outreachy-django-wagtail#project-and-mentorapproval-classes)
 * Login as your superuser account. Go to the internship round project list page at `http://localhost:8000/apply/project-selection/`. When you click on the project title at the bottom of the page, you'll be taken to the project description page. You can check the section you changed to ensure the commas are visible.

**Comment by getschomp** [comment]
Will work on this

**Comment by getschomp** [comment]
PR is open.  I was thinking it would be cool if there was one script to run to set up some of the needed models here. i.e. these steps.  Might help new contributors.

> Make a new round with the contribution period open, following the instructions in README.md.
> Create two or more coordinator accounts under the same community.
> Create a Participation object that has the community participating in the newly created round.
> Create a project under the community with a mentor
> Start the local test website server
