### ISSUE TITLE
Broken link on community CFP page

### ISSUE THREAD

**Issue by sagesharp** [outreachy/website#330]
Ben Nemec (who was an OpenStack mentor in the May 2019 application round) reports:

Just wanted to let you know that there are a couple of broken links on https://www.outreachy.org/communities/cfp/openstack/

The "mentor requirements" under the "Submit an Outreachy Intern Project Proposal" and "Co-mentor an Intern" sections point to https://www.outreachy.org/communities/cfp/openstack/mentor/#mentor which doesn't work. It looks like they should point at https://www.outreachy.org/mentor/#mentor

**Comment by sagesharp** [comment]
The template this bug is in is here (should be a / in front of mentor in the URL): https://github.com/outreachy/website/blob/master/home/templates/home/community_read_only.html#L149

**Comment by AnkitMishra17** [comment]
I'd like to take this issue.

**Comment by sagesharp** [comment]
@AnkitMishra17 Go for it! There's instructions in the README about how to set up your local environment for testing. You'll need to follow the instructions for setting up a new round with a community participating in that round.

Note that I believe the page referenced is in the Outreachy website CMS, not in the code base. When this bug is fixed, I think you'll get a 404 error. As long as the URL in your browser's address bar is the correct one, your fix should be correct.
