### ISSUE TITLE
Adding Contributor Covenant Code of Conduct

### ISSUE THREAD

**Issue by tapaswenipathak** [outreachy/website#343]
Hey maintainers: Can the project has Contributor Covenant Code of Conduct added https://en.wikipedia.org/wiki/Contributor_Covenant?

**Comment by djmitche** [comment]
Outreachy's code of conduct is https://github.com/outreachy/website/blob/master/CODE-OF-CONDUCT.md.  Is there something specific missing in that document?

**Comment by tapaswenipathak** [comment]
On Sat, Aug 24, 2019 at 6:49 PM Dustin J. Mitchell
<notifications@github.com> wrote:
>
> Outreachy's code of conduct is https://github.com/outreachy/website/blob/master/CODE-OF-CONDUCT.md. Is there something specific missing in that document?

Thanks, I thought the doc is for Outreachy Internships, closing.  Feel
free giving a thought if you require a Contributor Covenant Code of
Conduct from https://www.contributor-covenant.org/ as well.

>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Thanks,
Tapasweni
