### ISSUE TITLE
Update Funding link is not working on the community CFP page

### ISSUE THREAD

**Issue by pranavjain** [outreachy/website#349]
[Update Funding link]( https://www.outreachy.org/december-2019-to-march-2020-internship-round/communities/debian/submit/) on the [community CFP](https://www.outreachy.org/communities/cfp/debian/) page is giving a Page Not found error.

**Comment by nerdyvaishali** [comment]
@sagesharp I'm getting the same error as well. If it's possible can you please look into it. Thanks.
