### ISSUE TITLE
Rejected co-mentor gets cc'ed in outgoing emails

### ISSUE THREAD

**Issue by muarachmann** [outreachy/website#359]
Looks like co-mentors who got rejected during the application phase gets cc'ed on every email sent out like intern selection etc, I just got a mail about the intern selected and behold a rejected co-mentor was being cc'ed. I guess this is not the intended behavior @sagesharp any inputs on this?

**Comment by muarachmann** [comment]
More can be found here opened by our org admin - https://chat.outreachy.org/#narrow/stream/29-Mentors-.26.20Coordinators/topic/BUG.3A.20rejected.20mentor.20getting.20emails.20from.20Outreachy/near/9950

**Comment by sagesharp** [comment]
Thanks for letting me know @muarachmann. I think I see the issue in the code, but it's pretty pervasive so I want to make sure I've caught all the instances. As a temporary work-around, I've deleted any rejected mentors from the Outreachy website.

**Comment by muarachmann** [comment]
seems ok

**Comment by sagesharp** [comment]
Fixed, and a new test is in place to make sure this doesn't happen again. Thanks for reporting, @muarachmann!
