### ISSUE TITLE
Project Setup: Error during the installation in local machine

### ISSUE THREAD

**Issue by Aju100** [outreachy/website#364]
#### Description
With respect to developers and opensource enthusiasts, I am trying to contribute to this project so I got some problems during installation in my local machine. 

#### Screenshots
![outreachy](https://user-images.githubusercontent.com/29862610/72306665-0c76c900-36a0-11ea-88d2-39377f901509.png)

#### To Reproduce
-[ ] clone the repo 
-[ ] follow the installation guide
-[ ] pipenv shell
-[ ] pipenv install
-[ ] error

### System I have used
- ubuntu 19.x 
- python 3.7

**Comment by TeAmP0is0N** [comment]
@Aju100 Can you send a log file of this failed installation?

**Comment by Aju100** [comment]
@TeAmP0is0N  you can check in your repo too.

**Comment by Aju100** [comment]
@TeAmP0is0N  I didn't get the point. Can you please give more info what you are explaining ?

**Comment by TeAmP0is0N** [comment]
@Aju100 read the last line of your image which you have sent. I want that log file.

**Comment by Aju100** [comment]
ok @TeAmP0is0N

**Comment by Aju100** [comment]
@TeAmP0is0N  It works  Thank you

**Comment by Aju100** [comment]
@TeAmP0is0N  here is the latest commit 5a4bc27670d941ee5719e2509403e39c0af3d1db

**Comment by sagesharp** [comment]
@Aju100 Why did you run pipenv shell before you ran pipenv install? The directions say: "Make sure that you are in the website directory first, and have not run pipenv shell yet, then run pipenv install"

**Comment by sagesharp** [comment]
Hi @Aju100. Did you manage to figure out the issue with setting up the website development environment? Since you haven't replied in one week, I'm going to close this issue. Please reopen it if you're still seeing the problem after trying the solution above. Or re-open a new issue if you're facing a different error message.

**Comment by Aju100** [comment]
@sagesharp thank you so much. It has been resolved.
