### ISSUE TITLE
Does not allow applicant to go to previous step without answering essay

### ISSUE THREAD

**Issue by deeptimahesh** [outreachy/website#365]
Preventing applicants (filling in their initial application) from accessing the next step makes sense, however, preventing them from going to the previous step to modify answers does not.

**Comment by sagesharp** [comment]
Unfortunately that's how form validation works for the Django extension we're using. When you have a multi-step form that uses the [django-formtools wizard](https://django-formtools.readthedocs.io/en/latest/wizard.html#usage), each step has to be validated before you go to the next or previous steps.

I agree it's not intuitive behavior, but it's not something we can fix. Closing this issue.
