### ISSUE TITLE
'postcss' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Aju100** [outreachy/website#367]
I have followed the instructions and install this repo. I have migrated too. After it, I tried to run on my localmachine but seems error.

![post](https://user-images.githubusercontent.com/29862610/73804999-8dcc0200-47ed-11ea-9980-e4d2027dbe06.PNG)

**Comment by sagesharp** [comment]
@Aju100 What command are you using to run the webserver? E.g. the one that includes 'runserver'? Did you start the virtual environment and then run the `npm install` command? My guess is that either a) you don't have the right npm packages installed in your Python virtual environment, or b) you aren't pointing the web server to the path for the npm packages.

**Comment by sagesharp** [comment]
What would help is a screen shot of the exact commands you're running, including the list of files in the directory you're in when you run those commands.
