### ISSUE TITLE
Nav Bar in the website is uppercutted

### ISSUE THREAD

**Issue by kushthedude** [outreachy/website#369]
The navigation bar on outreachy.org is uppercutted. 
 
#### Screenshot :
<img width="1248" alt="Screenshot 2020-02-08 at 4 47 50 PM" src="https://user-images.githubusercontent.com/44091822/74084209-e4a63580-4a92-11ea-8ddd-9eeaeb99b73c.png">

#### Device : 
OS : MacOS Mojave
Browser: Safari

**Comment by kushthedude** [comment]
Ping @sagesharp

**Comment by djmitche** [comment]
Hm, I don't see that.  Is that black bar from a browser extension of some sort?

**Comment by kushthedude** [comment]
> Hm, I don't see that. Is that black bar from a browser extension of some sort?

That black is browser tab bar and it is on top, As you can see the navbar is cutted from above

**Comment by sagesharp** [comment]
@kushthedude What web browser are you using?

**Comment by kushthedude** [comment]
I am on Safari.

**Comment by kushthedude** [comment]
> And do you have a custom theme / skin installed?

No custom theme/skin

**Comment by kushthedude** [comment]
Solved, I dont know if it was a flake or not. Thanks for your time @sagesharp @djmitche .
