### ISSUE TITLE
Outreachy home page type

### ISSUE THREAD

**Issue by oalbacha** [outreachy/website#384]
Hello,
I found a typo on the Outreachy home page while reading through so I thought I’d let you know about it:

![image](https://user-images.githubusercontent.com/17005317/83114268-d16ab480-a0d9-11ea-9205-ae512707533f.jpeg)

“Outreachy will be looking..” There is no need for the “is” here. 

Let me know what you decide, I am happy to submit a quick PR for this if needed. 

Omar

**Comment by sagesharp** [comment]
Thanks for spotting this, @oalbacha! The homepage isn't in this repo, it's stored in a database on the website CMS. So unfortunately you can't submit a pull request. But I will go fix it.

**Comment by sagesharp** [comment]
Fixed now! Thanks again for spotting this @oalbacha! :blue_heart:
