### ISSUE TITLE
Collect country in initial application

### ISSUE THREAD

**Issue by sagesharp** [outreachy/website#395]
Outreachy is going to be making some temporary changes to student eligibility for the December 2020 round. Non-students will still be eligible (pending a review of their time commitments). Students in the northern hemisphere will not be eligible for this round, even if they have enough days free. Only students in the southern hemisphere with 42 days free will be eligible for this round.

In order to expediate initial application processing, we need to collect the country where people are living. To do that:
 - [ ] Install [the Django address package](https://github.com/furious-luke/django-address)
 - [ ] Add an AddressField (or CountryField?) from that package as a new Class, with a ForeignKey to ApplicantApproval
 - [ ] Add a new wizard form to the initial application (or maybe just collect it on the first page?)
 - [ ] (Optional) - Add jquery UI to auto-suggest country names, so we don't get things like "Brazil" and "Brasil"

**Comment by krysal** [comment]
Is this still needed for future rounds? The [Django Countries](https://github.com/SmileyChris/django-countries) package provides a **CountryField** with a complete list of countries (ISO 3166-1), could be a good option too.

**Comment by sagesharp** [comment]
Thanks for asking! This issue should be closed, since we did add a country field to the initial application essay questions page.
