### ISSUE TITLE
Show intern round dates on each alum entry in alums page

### ISSUE THREAD

**Issue by sagesharp** [outreachy/website#452]
It's confusing to scroll through the [ Outreachy alums](https://www.outreachy.org/alums/) page. There are headings for what internship round each intern is accepted in (e.g. "December 2020 to March 2021"). However, it gets confusing as you scroll through the long list of interns. Because we list multiple cohorts on the same page, you can run across the same organization multiple times, and it's not clear which round that intern was selected for.

The Django template for the alums page is in `home/templates/home/alums.html`. Add an "Internship cohort:" line above the "COMMUNITY mentor(s):" line. List which internship cohort the person was accepted for.

You'll need to take a look at the `class InternSelection` in `home/models.py` to understand how the InternSelection model relates to the RoundPage model. The RoundPage model is the class that stores the information about the internship round name and dates.

You may need to read up about [Django's foreign keys](https://docs.djangoproject.com/en/1.11/ref/models/fields/#module-django.db.models.fields.related). If you are new to databases, we recommend reading about what a foreign key is:

 - [What is a primary key?](https://www.techopedia.com/definition/5547/primary-key)
 - [What is a foreign key?](https://www.techopedia.com/definition/7272/foreign-key)
 - [How do primary keys and foreign keys relate to each other?](https://database.guide/what-is-a-foreign-key/)

**Comment by KarenEfereyan** [comment]
I don't write django

**Comment by 96RadhikaJadhav** [comment]
@sagesharp I'm a newbie to Django. I want to work on the issue. I will start to work on it and will create a PR soon.

**Comment by sagesharp** [comment]
@96RadhikaJadhav Welcome to the Outreachy website repo! Please do work on this issue. When you have questions, please ask them by commenting on this issue. If you have trouble setting up your development environment, please also comment here with the error log.

**Comment by RiddhiAthreya** [comment]
@sagesharp is this issue still relevant? looks like different cohorts are on different pages

**Comment by sagesharp** [comment]
@RiddhiAthreya Yep, you're correct. The alums page has been split into different cohorts, so this should be closed.
