### ISSUE TITLE
Clarify eligibility WRT employment

### ISSUE THREAD

**Issue by sagesharp** [outreachy/website#473]
Outreachy applicants have expressed confusion about our rules around part-time employment during the Outreachy internship. Therefore, we need to clarify the wording on our [eligibility rules](https://www.outreachy.org/apply/eligibility/) page.

In the [home/templates/home/snippet/eligibility_rules.html file](https://github.com/outreachy/website/blob/master/home/templates/home/snippet/eligibility_rules.html) change this bullet point:

"Applicants who have part-time or contracting jobs are welcome to apply. People who are willing to quit their full-time job are welcome to apply. If you cannot quit your full-time job, you are not eligible for Outreachy. People who are taking a leave of absence from a full-time job are not eligible for Outreachy."

to be one bullet point with two paragraphs:

"Applicants who have part-time or contracting jobs are welcome to apply. However, part-time jobs must be approved by Outreachy organizers. People who are willing to quit their full-time job are welcome to apply. If you cannot quit your full-time job, you are not eligible for Outreachy. People who are taking a leave of absence from a full-time job are not eligible for Outreachy."

"Applicants are required to list their current jobs and internships on their initial application. If an applicant receives a job or internship offer after submitting an initial application, they should [notify Outreachy organizers immediately](https://www.outreachy.org/contact/organizers/). Applicants are required to document any changes from the time commitments listed on their initial application, by filling out the question about time commitment changes in their final applications."

Verify that your changes are properly displayed by [following the README instructions to get your local website environment set up](https://github.com/outreachy/website#setting-up-your-development-environment). Start the local webserver. Then you navigate to [http://localhost:8000/apply/eligibility/](http://localhost:8000/apply/eligibility/) to verify you can see your changes.

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can anyone suggest me ways to get started?
