### ISSUE TITLE
Remove travel stipend refrence in intern intro email

### ISSUE THREAD

**Issue by sagesharp** [outreachy/website#474]
The email we send to Outreachy interns mentioned the Outreachy travel stipend. That travel stipend is no longer used.

Remove the following text from [home/templates/home/emails/interns-notify.txt](https://github.com/outreachy/website/blob/master/home/templates/home/email/interns-notify.txt):

```
Travel Allowance
----------------

You have $500 travel allowance available to you for travel relevant to Outreachy. The travel allowance is good for one year from the date your internship starts. Please review the information at https://www.outreachy.org/travel-stipend

You will need to discuss the travel stipend with your mentor to determine which conference or event is most relevant to your internship. You mentor will need to approve the conference or event before you book your travel.

Please note that before you book any flights, you will need to take a screenshot of your flight search using a widely-recognized airfare comparison site, such as Orbitz, Kayak or Hipmunk. You should also double check before booking travel if you will need to seek pre-approval from the Outreachy organizers for the travel. https://www.outreachy.org/travel-stipend#preapproval If you don't need pre-approval, and your mentor approves the travel as relevant to your internship, there is no need to email the organizers before your travel.
```

You will need to test that the email looks correct. Run the following shell commands to set up the website to be during the internship week 1.

```
$ ./manage.py shell
>>> from home import scenarios
>>> scenario = scenarios.InternshipWeekScenario(week=1)
```
(Note: if you already ran a scenario function in the Django shell, you may need to remove db.sqlite3, and rerun the migate and createsuperuser commands. This will remove your local database. Then run the above commands.)

Related to #459

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can anyone suggest me ways to get started?

**Comment by richach** [comment]
Hi Community, I am Richa. I am new to this community and I would like to work on the issue code #474. Thank you!
