### ISSUE TITLE
Incorrect detail in the README.md file. 

### ISSUE THREAD

**Issue by Mercysticks** [outreachy/website#530]
The Amount to be paid in the README.md file does not reflect the amount to be paid to interns on Outreachy's website. Instead of $7,000, $6,000 was written in the README.md file.

**Comment by taniaduggal** [comment]
@Mercysticks it means it must be $7000 in readme

**Comment by impeccable16** [comment]
hey @Mercysticks 
I am new here , could you please tell me how should I contribute in your issue?

**Comment by Mercysticks** [comment]
@impeccable16 I am so sorry. 
I created the issue and I have made commensurate contribution to the issue and my PR has been merged. 
Thanks. You could look up other open issues as I will close this now. 
Thanks.
