### ISSUE TITLE
Incorrect date on the website for Outreachy December internships

### ISSUE THREAD

**Issue by SaxenaAnushka102** [outreachy/website#541]
## Description
The Date for winter internships is mistakenly written as "December 2024 internships", instead of "December 2023 internships" under the "Important dates" section on the [Outreachy website](https://www.outreachy.org/), .

## Screenshot
![Screenshot (194)](https://user-images.githubusercontent.com/58849657/214830033-996b97c6-6d19-4817-ba6d-1f821d4c6cb2.png)

## To Reproduce
We need to modify "December 2024 internships" to "December 2023 internships".

**Comment by KartikPatil20** [comment]
I got it. I can solve this problem if you assign this issue to me.

**Comment by KartikPatil20** [comment]
I got it. I can solve this problem if you assign this issue to me.

**Comment by SaxenaAnushka102** [comment]
Hi @KartikPatil20! You can try asking the maintainers to assign you because I don't have the access to assign the issue to you.

**Comment by nitheesh-daram** [comment]
@KartikPatil20 @SaxenaAnushka102 looks likes data is being injected from DB and not hardcoded anywhere.so I think it's need to be corrected in db.

**Comment by SaxenaAnushka102** [comment]
Oh okay, if that's the case then you can take it up @nitheesh-daram. Please ask the maintainers to assign the issue to you, all the best!

**Comment by felixsunyk** [comment]
hi @SaxenaAnushka102 @KartikPatil20 @nitheesh-daram. I can solve the problem
