### ISSUE TITLE
Fix contribution period duration in Mentor Duties and Responsibilities section

### ISSUE THREAD

**Issue by jufajardini** [outreachy/website#581]
When enrolling as mentors, we are directed to read https://www.outreachy.org/mentor/#mentor
this indicates that the contribution period is of 6 weeks.

I'm not sure what's the best approach here - if changing to 4 would be good enough, or using a range.

Once that is defined, I can try to find the right place to fix it, and submit a fix.

**Comment by TildaDares** [comment]
Hi @jufajardini, thank you pointing this out and opening this issue.

You're correct about the duration. It should be 4 weeks. 

However, the change can only be made on our CMS and not on this repository. 

I'll update that page and let you know once the change is made.

**Comment by jufajardini** [comment]
> That page has been updated. Please let me know if I caught all the issues on that page.
> 
> Thank you!

Hello, the instances that I had noticed are fixed, thanks! (didn't close the issue as I don't know if you prefer that have maintainers do that)

**Comment by TildaDares** [comment]
Thank you for the confirmation!
