### ISSUE TITLE
Minor Grammar Improvements in 'Define a Project' Section of Pre-Application Process Guide"

### ISSUE THREAD

**Issue by Mayaleeeee** [outreachy/website#588]
## Description
In the "Define a Project" section under Pre-Application Process (third paragraph), there are a couple of small grammar issues that could improve readability.

Here's a screenshot of the page 
![Screenshot_20241031_155749_Chrome](https://github.com/user-attachments/assets/cff67652-eddc-48d8-9e73-f511bf6f2cc3)

## How to reproduce?
- Change **"It's fine to for communities..."** to **"It's fine for communities..."** to remove an extra "to."
- Change **"That give applicants a choice of projects"** to **"That gives applicants a choice of projects"** to fix subject-verb agreement.

These tweaks will make the instructions a bit clearer.

I'm very happy to work on this issue.

cc @sagesharp @TildaDares

**Comment by TildaDares** [comment]
Hi @Mayaleeeee, thank you for reporting this issue. Can you share the url to the page with these typos? Thank you!

**Comment by TildaDares** [comment]
@Mayaleeeee You're correct about the typo. However, the change can only be made on our wagtail CMS and not on this repository.

I've updated the page, please let me know if the issue has now been fixed. 

Thank you!

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee You're correct about the typo. However, the change can only be made on our wagtail CMS and not on this repository.
> 
> I've updated the page, please let me know if the issue has now been fixed. 
> 
> Thank you!



It's alright @TildaDares 
Thanks for the update.
